### ISSUE TITLE
Is it possible to get access to component during start method?

### ISSUE THREAD

**Issue by loolo78** [Thundernerd/Unity3D-ComponentAttribute#1]
Is it even reasonable to ask that or is that a code smell of some sort?

**Comment by Thundernerd** [comment]
If you mean that the components are available when the start method gets executed then yes, they are accessible at that time. 
Depending on what version you are using you can also get then in Awake.
Versions below 1.2 have the extendedbehaviour and the extension methods so you can get the components in Awake, Start, OnEnable, whenever you want really.
From 1.2 on there's no extendedbehaviour or extension method anymore so they are only available from when Start gets called.

If you have any other questions feel free to ask!

**Comment by loolo78** [comment]
Thank you for making such a nice script and sharing it on GitHub. Don't forget to update your unitypackage file, it wasn't working because I was using an older version of the asset that came from the unitypackage.

**Comment by Thundernerd** [comment]
Thanks, I'll make sure to update it soon!
